### ISSUE TITLE
Work with typescript

### ISSUE THREAD

**Issue by darbio** [mj1618/serverless-localstack-sns#1]
Hi @mj1618,

Any chance you can port the changes you made in serverless-offline-sns to this repo?

Cheers,
darbio

**Comment by mj1618** [comment]
hey @darbio !

Interesting question, would be good to understand your use case.

The idea of serverless-offline-sns is actually to be able to work with localstack as well. So if you just put the URL to localstack as your sns-endpoint then serverless-offline-sns will go to localstack rather than it's own sns server.

Does this sound like it would cover your use case? If so I might decomission this project.

**Comment by darbio** [comment]
Sorry for the late reply - yes, this works and it makes sense to decommission this project in favour of the single repo.
